name: Deploy to Server1

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# .github/workflows/deploy.yml
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        # Put your private key in repo secret: SSH_PRIVATE_KEY
        - name: Start ssh-agent and add private key
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
        - name: Trust host
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H 13.215.192.207 >> ~/.ssh/known_hosts
  
        - name: Your SSH command
          run: ssh -o StrictHostKeyChecking=yes user@13.215.192.207 "uname -a"
  